    - Chosen dataset:
A non-store online retail that focuses on gift-ware and is based in the UK, and that company's transaction history between 1st of December, 2009 until 9th of December, 2011.

    - Business problem:
To which extent are the customers willing to buy another product from Online Retail II within 60 days of another purchase, hence showcasing their loyalty to the company?

    - Why is it important?:
Marketing uses a lot more resources for various store perks, such as coupon codes. These perks often get used up by customers that may either never make another purchase from this company or by customers that would come back no matter if they got that perk or not.
Due to this, it is very important to analyse how often customers buy products from this company as well as the amount of time that passes between each purchase, to determine their 'loyalty'. 

    - Benefits:
Being able to identify the 'loyalty' of a customer is very significant, as that way, marketing would know where to delegate its resources more effectively.
In addition to perks becoming more targeted, as the customers are being paid attention to more closely, this would most likely to a general increase in the customer base, as more people would end up buying from this company.

    - How will we know if its beneficial or not?
A way to do this would be to constantly update the database and comparing the results. Some examples would be, if the changes made in marketing are effective, there might be either more customers returning back to buy from this company or just an overall higher number of customers than what the online retail started with.

    - How is the relevant data being collected?
For this assignment, I am using a dataset. Although in an actual setting, the company would first start by collecting the information regarding the purchases. The details of the transaction history would focus on the same features as the columns in the dataset that I am using. 
To add on, the company could also send out surveys with additional bonuses that focuses on collecting the customer's feelings, thus testing their loyalty and likeness to come back to make another purchase soon. This type of engagement does not necessarily need to buy a survey, but it needs to be able to collect the relevant information.

    - Formulating this problem as a machine learning task:
This problem uses the idea of a binary classification task, which takes the customer purchase history before the cutoff date and assigns them the label 1 if they made another purchase in the 60 days after the cutoff. If not, they are assigned the label 0. The model learns the patterns as well as the relationship between the purchasing behaviour and the possibility of the customer coming back within that time frame. Such a model hence is able to turn 'loyalty' into a metric that is not only predictable, but also measurable by specific features, allowing marketing to have a clearer understanding of their customer base and to minimize misallocating the costs.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('online_retail.csv')

Data Exploration

In [ ]:
print(df.shape) #Shows that there are 1067371 rows and 8 columns.

(1067371, 8)

In [4]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
df.describe().T[['mean', 'std', 'min', 'max']].head()

                     mean          std       min      max
Quantity         9.938898   172.705794 -80995.00  80995.0
Price            4.649388   123.553059 -53594.36  38970.0
Customer ID  15324.638504  1697.464450  12346.00  18287.0

In [6]:
df.dtypes #To understad which data types the dataset contains

Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

In [7]:
df.describe

<bound method NDFrame.describe of         Invoice StockCode                          Description  Quantity  \
0        489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1        489434    79323P                   PINK CHERRY LIGHTS        12
2        489434    79323W                  WHITE CHERRY LIGHTS        12
3        489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4        489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24
...         ...       ...                                  ...       ...
1067366  581587     22899         CHILDREN'S APRON DOLLY GIRL          6
1067367  581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
1067368  581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
1067369  581587     22138        BAKING SET 9 PIECE RETROSPOT          3
1067370  581587      POST                              POSTAGE         1

                 InvoiceDate  Price  Customer ID         Country
0        2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2        2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3        2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4        2009-12-01 07:45:00   1.25      13085.0  United Kingdom
...                      ...    ...          ...             ...
1067366  2011-12-09 12:50:00   2.10      12680.0          France
1067367  2011-12-09 12:50:00   4.15      12680.0          France
1067368  2011-12-09 12:50:00   4.15      12680.0          France
1067369  2011-12-09 12:50:00   4.95      12680.0          France
1067370  2011-12-09 12:50:00  18.00      12680.0          France

[1067371 rows x 8 columns]>

In [10]:
print("Throughout the dataset, there are", df.duplicated().sum(), "duplicate rows.")

Throughout the dataset, there are 34335 duplicate rows.

Data Preprocessing